### PR TITLE
travis: add Foxy CI build

### PR DESCRIPTION
**Pull request by mvegter**
Added latest ROS2 distribution.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
> it would be nice to include a ROS2 distro in the CI builds.

So `dashing` and `eloquent` are not "ROS2 distro[s]"?

**Comment by mvegter** [comment]
@gavanderhoorn Whoops, I have changed the description 😅

**Review by jontje — APPROVED** [review]
Looks good to me

**Comment by jontje** [comment]
Thanks for the PR @mvegter 👍

**Pull request merged**
