### PR TITLE
Clarified the log content, and added fast transition for static goals

### PR DESCRIPTION
**Pull request by jontje**
* Added default headers to the log, as well as the planned information (from the robot controller)
* Added option for fast transition for static goals (i.e. used in the EGMTrajectoryInterface class)

### CODE REVIEW

**Comment by jontje** [comment]
@gavanderhoorn I have fixed the compilation error, I had used ofstream's open(string&, ...) method instead of open(char*, ...). The one with string& is for C++11

**Comment by gavanderhoorn** [comment]
We can of course enable C++11 support for the pkg, but I feel it has to be a concious decision. Do you have any internal guidelines for which platforms / compilers you intend to support?

**Comment by gavanderhoorn** [comment]
Feel free to merge @jontje.

**Comment by jontje** [comment]
@gavanderhoorn Thanks for the review and the comments! 👍

And, no, I don't have any guidelines for that at the moment. Also, yes, unit-tests would be good to add.

**Pull request merged**
