### PR TITLE
The original codebase of the library

### PR DESCRIPTION
**Pull request by jontje**

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
A minor comment would be whether this should really be version `1.0.0`. We (try to) use [semantic versioning](https://semver.org/) for non-experimental repositories, so labelling this as `1.0.0` should not be taken lightly.

**Comment by gavanderhoorn** [comment]
Feel free to merge this @jontje.

If I may suggest: use a squash-and-merge (dropdown). I don't feel a particular need to keep the fixup commit around. But I'll leave it to you.

**Comment by gavanderhoorn** [comment]
I'll post some issues to capture some of the things we can improve after you merge this PR.

**Comment by jontje** [comment]
I have reverted to the "initial codebase" commit to make the PR more clear

@gavanderhoorn: Thanks a lot for the previous review, and the discussion we had after that. Please redo the review when you find the time.

**Comment by gavanderhoorn** [comment]
Feel free to merge this @jontje.

**Pull request merged**
