### PR TITLE
Rebased version of #23 (install protobuf headers)

### PR DESCRIPTION
**Pull request by gavanderhoorn**
This is all work done by @traversaro.

Just a rebase by me (no need to maintain history, as it's a fairly stand-alone change).

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
I've also added 4aa687b which install the `.proto` files, following the suggestion by @traversaro in #23.

Not sure the `include/abb_libegm` directory is the best place for them though, but I'm not an expert, so let's go with that for now.

**Comment by gavanderhoorn** [comment]
I'd :+1: this, but I need another maintainer to do that, so @jontje I've requested a review from you.

**Comment by traversaro** [comment]
> Not sure the `include/abb_libegm` directory is the best place for them though, but I'm not an expert, so let's go with that for now.

The [`ignition-msgs`](https://bitbucket.org/ignitionrobotics/ign-msgs) library that install `.proto` files used by ignition-gazebo do that for the official debian package that are consistent with debian packaging guidelines, so I guess that is ok:
https://packages.debian.org/sid/amd64/libignition-msgs-dev/filelist

**Comment by gavanderhoorn** [comment]
Well .. Debian isn't the end-all-be-all, but OK. Let's keep it like this for now.

**Comment by gavanderhoorn** [comment]
Hm, wait. There could be an `include` too many in the `install(..)` path.

**Comment by traversaro** [comment]
> Well .. Debian isn't the end-all-be-all, but OK. Let's keep it like this for now.

Agreed. I am afraid there is not widely agreed convention for where to install `.proto` files, you just need to know where they are installed to pass the path to the protobuf compiler `-IPATH` option. The use of include directories is just convenient so you can re-use all the build system  machinery used to propagate the correct include directory to the preprocessor's `-I` or `-Isystem` options.

**Comment by gavanderhoorn** [comment]
Ok, so with X, the headers end-up in `$CATKIN_WS/install/include/abb_libegm/include/abb_libegm`, which seems one `include/abb_libegm` to many to me.

**Comment by traversaro** [comment]
> Ok, so with X, the headers end-up in `$CATKIN_WS/install/include/abb_libegm/include/abb_libegm`, which seems one `include/abb_libegm` to many to me.

Sorry for the trouble, not sure why it was like that originally (some time passed). That would explain why the PR did not solved the problem in https://github.com/ros-industrial/abb_libegm/issues/7#issuecomment-475894855 .

**Comment by gavanderhoorn** [comment]
No need to apologise @traversaro. Just noticed it myself.

It looks like the current `install(..)` target for the headers ([this one](https://github.com/ros-industrial/abb_libegm/blob/80111ca50459bfe2b07c40d94ed06731cd2d4e82/CMakeLists.txt#L76-L78)) is the cause here.

**Comment by gavanderhoorn** [comment]
@jontje: did you have any particular reason to use the current command (ie: [this](https://github.com/ros-industrial/abb_libegm/blob/80111ca50459bfe2b07c40d94ed06731cd2d4e82/CMakeLists.txt#L76-L78)) to install the headers?

I've never noticed, but that particular way of calling `install(..)` results in headers (all of the, not just the protobuf related ones) getting installed in `$CATKIN_WS/install/include/abb_libegm/include/abb_libegm`, which would be one `include/abb_libegm` too many.

I'm going to assume this was not intentional and I'll include a commit here to normalise the situation to `$CATKIN_WS/install/include/abb_libegm`. Both regular and protobuf headers would then install there.

**Comment by gavanderhoorn** [comment]
I've added 3126f6d which installs all headers into the regular (in a ROS context anyway) `include/abb_libegm`.

Not sure how this interacts with #24, but we'll take a look at that later.

**Comment by gavanderhoorn** [comment]
@jontje: could you perhaps check whether the examples that you're working on are ok with this change?

I'd still like to merge this as-is, so even if the examples fail to build we'd need to update those, but it'd be good to know what we break.

Note: things will only break if you're using an *install space*. Regular builds against `devel` and `build` spaces are not affected.

**Comment by jontje** [comment]
> @jontje: did you have any particular reason to use the current command (ie: [this](https://github.com/ros-industrial/abb_libegm/blob/80111ca50459bfe2b07c40d94ed06731cd2d4e82/CMakeLists.txt#L76-L78)) to install the headers?

No reason, I am not very proficient with creating CMakeList files and it seemed to work for me earlier. Thanks for fixing it! 👍

> @jontje: could you perhaps check whether the examples that you're working on are ok with this change?

I will check it later, but this looks fine for me.

**Comment by gavanderhoorn** [comment]
Ok.

I'm going to rebase this one last time and then merge.

**Comment by jontje** [comment]
@traversaro: Thanks for the original PR 👍

**Comment by gavanderhoorn** [comment]
Apologies @jontje: with the force push I've just dismissed your review.

Could you approve again?

**Comment by gavanderhoorn** [comment]
Thanks @traversaro for the PR and thanks @jontje for the review.

**Pull request merged**
