### PR TITLE
Add GitHub Action job for installation on Windows using vcpkg

### PR DESCRIPTION
**Pull request by traversaro**
I think I can't create a new workflow in a PR, so I will try to first test in in my fork.

### CODE REVIEW

**Comment by traversaro** [comment]
The CI job seems to be working fine https://github.com/traversaro/abb_libegm/runs/664911839?check_suite_focus=true , but it is relatively slow, i.e. 10 minutes to build the dependencies, so it is probably worth to setup some caching before merging it.

**Comment by gavanderhoorn** [comment]
@traversaro: did you close this on purpose?

**Comment by gavanderhoorn** [comment]
Seems the build fails actually (or: the install phase):

```
2020-05-11T21:54:21.1474058Z CMake Error at cmake_install.cmake:40 (file):
2020-05-11T21:54:21.1474464Z   file INSTALL cannot find "D:/a/abb_libegm/abb_libegm/build/egm.pb.h": No
2020-05-11T21:54:21.1474723Z   such file or directory.
```

**Comment by traversaro** [comment]
> 
> 
> @traversaro: did you close this on purpose?

Yes, as mentionen in the previous comment and in your comment there are other failures (in the install), so I will work on it on my own and then I will open the PR when it is actually working.

**Pull request closed without merging**
