### PR TITLE
readme: use GHA badges

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
I've opted to distribute the badges over two 'rows', as I thought it'd otherwise become too many badges on a single line.

Depending on preference, we could revert it to be on a single line of course.

**Comment by jontje** [comment]
> I've opted to distribute the badges over two 'rows', as I thought it'd otherwise become too many badges on a single line.
> 
> Depending on preference, we could revert it to be on a single line of course.

Multiple lines are fine with me.

Maybe even make it three lines similar to e.g. abb_robot_driver's [README](https://github.com/ros-industrial/abb_robot_driver/blob/486badc59fe5a6a2d589875dc3b9a39a663e4582/README.md)?

**Comment by gavanderhoorn** [comment]
Good suggestion. I've done that.

I've also added an "open issues" badge, similar to the `abb_robot_driver` readme.

**Review by jontje — APPROVED** [review]
Looks good to me 👍

**Comment by gavanderhoorn** [comment]
Thanks for the review.

**Pull request merged**
