### PR TITLE
Install generated protobuf headers

### PR DESCRIPTION
**Pull request by traversaro**
Fix https://github.com/ros-industrial/abb_libegm/issues/7 .

Some projects (Gazebo and ign-msgs in particular) also install the  `.proto` files to permit to downstream users to define their own protobuf  that use Gazebo-defined protobuf data structures (see http://gazebosim.org/tutorials?tut=custom_messages). If we are interested in that use case, it is possible to also install the `.proto` files as: 
~~~cmake
install(FILES ${EgmProtoFiles}
        DESTINATION ${CATKIN_PACKAGE_INCLUDE_DESTINATION}/include/${PROJECT_NAME})
~~~

### CODE REVIEW

**Comment by jontje** [comment]
Thanks for the PR @traversaro!

My schedule is a bit full at the moment, but I will take a closer look as soon as I find some time :)

**Comment by gavanderhoorn** [comment]
I've submitted a rebased version of this in #43.

**Comment by gavanderhoorn** [comment]
Thanks for submitting this one @traversaro. Much appreciated.

**Comment by traversaro** [comment]
Thanks for merging!

**Pull request closed without merging**
